[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[redirects]]
  from = "/api/*"
  to = "http://34.172.224.16/:splat"
  status = 200
  force = true